### ISSUE TITLE
Keywords missing in PDF

### ISSUE THREAD

**Issue by augla** [grasshopper7/cucumber-pdf-report#11]
For readability of the scenarios the Cucumber keywords are important, but these are not shown in the PDF file

**Comment by grasshopper7** [comment]
Can u add a screenshot for this? I think this is being displayed. Are u using the maven plugin to generate report or the extent adapter?

**Comment by augla** [comment]
Very nice that you respond so quickly!
The screenshot:
![image](https://user-images.githubusercontent.com/62107569/103675837-b0781500-4f80-11eb-99f6-8256bdfe8b54.png)

I use tech.grasshopper:cucumber-pdf-plugin:1.2.0 and tech.grasshopper:cucumber-pdf-report:1.7.0 (or 1.6.0).
I copied a bit of the glue code as people can generate it on demand from a web page: 
`	public static File generatePdf(File jsonPath, File pdfFolder) {
		final ReportProperties reportProperties = new ReportProperties();
		final CucumberPDFReportLogger logger = new CucumberPDFReportLogger();
		final JsonFileConverter jsonFileConverter =
				new JsonFileConverter(new EmbeddedProcessor(reportProperties, logger), logger);
		final List<Feature> features =
				jsonFileConverter.retrieveFeaturesFromReport(singletonList(jsonPath.toPath()));
		new HierarchyProcessor(reportProperties).process(features);

		PDFCucumberReportDataGenerator generator = new PDFCucumberReportDataGenerator();
		ReportData reportData = generator.generateReportData(features);

		PDFCucumberReport pdfCucumberReport =
				new PDFCucumberReport(reportData, pdfFolder.getAbsolutePath());
		pdfCucumberReport.createReport();
		return new File(pdfFolder, "report.pdf");
	}`

**Comment by grasshopper7** [comment]
Have added a new version in maven. Try and let me know. plugin version 1.3.0 will get the latest 2.0.0 version of the report.

**Comment by grasshopper7** [comment]
Reversed this as was adding double keywords for pdf generated by adapters. Changed the code in plugin to add keyword to step details

**Comment by sebinjoseph1994** [comment]
@augla Hi, 

public static File generatePdf(File jsonPath, File pdfFolder) {
final ReportProperties reportProperties = new ReportProperties();
final CucumberPDFReportLogger logger = new CucumberPDFReportLogger();
final JsonFileConverter jsonFileConverter =
new JsonFileConverter(new EmbeddedProcessor(reportProperties, logger), logger);
final List features =
jsonFileConverter.retrieveFeaturesFromReport(singletonList(jsonPath.toPath()));
new HierarchyProcessor(reportProperties).process(features);

	PDFCucumberReportDataGenerator generator = new PDFCucumberReportDataGenerator();
	ReportData reportData = generator.generateReportData(features);

	PDFCucumberReport pdfCucumberReport =
			new PDFCucumberReport(reportData, pdfFolder.getAbsolutePath());
	pdfCucumberReport.createReport();
	return new File(pdfFolder, "report.pdf");
}

Does the above code is something custom created by you or is it the way we can use the cucumber-pdf-report via code instead of a plugin?
